// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnTPBpkIh5SxELl5_YU-P7r_axRzohM4Q',
    appId: '1:870702312577:web:2eb02d5b5a3e69eb227180',
    messagingSenderId: '870702312577',
    projectId: 'bmi-calculate-94cee',
    authDomain: 'bmi-calculate-94cee.firebaseapp.com',
    storageBucket: 'bmi-calculate-94cee.appspot.com',
    measurementId: 'G-9475EQDTP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdbaURl7qXiRDncckEBTlqLjzBrKJ1qac',
    appId: '1:870702312577:android:29b7107ec1984fd6227180',
    messagingSenderId: '870702312577',
    projectId: 'bmi-calculate-94cee',
    storageBucket: 'bmi-calculate-94cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6OAp0OfHevyjdtSyWJe1mmNuJDv5S2o',
    appId: '1:870702312577:ios:b3235d00cc589301227180',
    messagingSenderId: '870702312577',
    projectId: 'bmi-calculate-94cee',
    storageBucket: 'bmi-calculate-94cee.appspot.com',
    iosBundleId: 'com.example.bmiCalculater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6OAp0OfHevyjdtSyWJe1mmNuJDv5S2o',
    appId: '1:870702312577:ios:e3524ec25a5efd5d227180',
    messagingSenderId: '870702312577',
    projectId: 'bmi-calculate-94cee',
    storageBucket: 'bmi-calculate-94cee.appspot.com',
    iosBundleId: 'com.example.bmiCalculater.RunnerTests',
  );
}
